//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeMetrics.Addin.Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.ICodeMetricsService")]
    public interface ICodeMetricsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeMetricsService/PerformTask", ReplyAction="http://tempuri.org/ICodeMetricsService/PerformTaskResponse")]
        CodeMetrics.DataTransferObjects.TaskResult PerformTask(CodeMetrics.DataTransferObjects.TaskRequest task);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICodeMetricsServiceChannel : CodeMetrics.Addin.Services.ICodeMetricsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CodeMetricsServiceClient : System.ServiceModel.ClientBase<CodeMetrics.Addin.Services.ICodeMetricsService>, CodeMetrics.Addin.Services.ICodeMetricsService {
        
        public CodeMetricsServiceClient() {
        }
        
        public CodeMetricsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CodeMetricsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodeMetricsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodeMetricsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CodeMetrics.DataTransferObjects.TaskResult PerformTask(CodeMetrics.DataTransferObjects.TaskRequest task) {
            return base.Channel.PerformTask(task);
        }
    }
}
